import { NextPage } from "next";
import Stripe from "stripe"
import Head from 'next/head'
import ProductsList from "../components/ProductsList"

export type Props = {
    products: {
        id: string;
        description: string | null;
        name: string;
        images: string[];
        unit_label: string | null | undefined;
        prices: {
            id: string;
            currency: string;
            transform_quantity: Stripe.Price.TransformQuantity | null;
            unit_amount: number | null;
        }[];
    }[]
}

export const getStaticProps = async () => {
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY ?? "", {
        apiVersion: "2022-11-15"
    })
    const products = await stripe.products.list()
    if(!products || products.data.length < 1){
        return []
    }

    const response = await Promise.all(products.data.map(async (resProduct: Stripe.Product) => {
        const prices = await stripe.prices.list({
            product: resProduct.id
        })
        return {
            id: resProduct.id,
            description: resProduct.description,
            name: resProduct.name,
            images: resProduct.images,
            unit_label: resProduct.unit_label,
            prices: prices.data.map(price => {
                return {
                    id: price.id,
                    currency: price.currency,
                    transform_quantity: price.transform_quantity,
                    unit_amount: price.unit_amount,
                }
            })
        }
    }))

    return{
        props:{
            products: response
        }
    }
}

const Home: NextPage<Props> = ({products}) => {
    return(
        <main>
        <Head>
          <title>EC-Site-Sample</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProductsList products={products} />
      </main>
    )
}

export default Home